package bdbeans;
// Generated 13 f�vr. 2025, 12:47:45 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours implements java.io.Serializable {

	private int idcours;
	private Etudiant etudiant;
	private String code;
	private String nomcours;
	private Set enseignants = new HashSet(0);
	private Set classes = new HashSet(0);

	public Cours() {
	}

	public Cours(int idcours) {
		this.idcours = idcours;
	}

	public Cours(int idcours, Etudiant etudiant, String code, String nomcours, Set enseignants, Set classes) {
		this.idcours = idcours;
		this.etudiant = etudiant;
		this.code = code;
		this.nomcours = nomcours;
		this.enseignants = enseignants;
		this.classes = classes;
	}

	public int getIdcours() {
		return this.idcours;
	}

	public void setIdcours(int idcours) {
		this.idcours = idcours;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNomcours() {
		return this.nomcours;
	}

	public void setNomcours(String nomcours) {
		this.nomcours = nomcours;
	}

	public Set getEnseignants() {
		return this.enseignants;
	}

	public void setEnseignants(Set enseignants) {
		this.enseignants = enseignants;
	}

	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
