package bdbeans;
// Generated 13 f�vr. 2025, 12:47:45 by Hibernate Tools 5.4.33.Final

/**
 * EtudiantId generated by hbm2java
 */
public class EtudiantId implements java.io.Serializable {

	private int idpers;
	private int idetud;

	public EtudiantId() {
	}

	public EtudiantId(int idpers, int idetud) {
		this.idpers = idpers;
		this.idetud = idetud;
	}

	public int getIdpers() {
		return this.idpers;
	}

	public void setIdpers(int idpers) {
		this.idpers = idpers;
	}

	public int getIdetud() {
		return this.idetud;
	}

	public void setIdetud(int idetud) {
		this.idetud = idetud;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtudiantId))
			return false;
		EtudiantId castOther = (EtudiantId) other;

		return (this.getIdpers() == castOther.getIdpers()) && (this.getIdetud() == castOther.getIdetud());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpers();
		result = 37 * result + this.getIdetud();
		return result;
	}

}
